In [1]:
from google.colab import files

uploaded = files.upload()

Saving archive.zip to archive.zip

In [2]:
import os

print(os.listdir())

['.config', 'archive.zip', 'sample_data']

In [5]:
import zipfile

zip_file = "archive.zip"

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("rainfall_data")

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [6]:
import os

for root, dirs, files in os.walk("rainfall_data"):
    for file in files:
        print(os.path.join(root, file))

rainfall_data/daily-rainfall-at-state-level.csv

In [8]:
import pandas as pd

rainfall = pd.read_csv("rainfall_data/daily-rainfall-at-state-level.csv")

display(rainfall.head())

,id,date,state_code,state_name,actual,rfs,normal,deviation
0,0,2009-01-01,5,Uttarakhand,0.0,0.003906,2.19,-100.0
1,1,2009-01-01,18,Assam,0.0,0.000000,0.52,-100.0
2,2,2009-01-01,16,Tripura,0.0,0.000000,0.09,-100.0
3,3,2009-01-01,36,Telangana,0.0,0.000000,0.17,-100.0
4,4,2009-01-01,2,Himachal Pradesh,0.0,0.008566,3.31,-100.0

In [9]:
print("Rows and columns:", rainfall.shape)
print("\nColumns:")
print(rainfall.columns.tolist())

Rows and columns: (204876, 8)

Columns:
['id', 'date', 'state_code', 'state_name', 'actual', 'rfs', 'normal', 'deviation']

In [10]:
rainfall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204876 entries, 0 to 204875
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          204876 non-null  int64
 1   date        204876 non-null  object
 2   state_code  204876 non-null  int64
 3   state_name  204876 non-null  object
 4   actual      187714 non-null  float64
 5   rfs         199011 non-null  float64
 6   normal      193358 non-null  float64
 7   deviation   173855 non-null  float64
dtypes: float64(4), int64(2), object(2)
memory usage: 12.5+ MB

In [11]:
print(rainfall.shape)
print(rainfall.columns.tolist())
display(rainfall.head())

(204876, 8)
['id', 'date', 'state_code', 'state_name', 'actual', 'rfs', 'normal', 'deviation']

,id,date,state_code,state_name,actual,rfs,normal,deviation
0,0,2009-01-01,5,Uttarakhand,0.0,0.003906,2.19,-100.0
1,1,2009-01-01,18,Assam,0.0,0.000000,0.52,-100.0
2,2,2009-01-01,16,Tripura,0.0,0.000000,0.09,-100.0
3,3,2009-01-01,36,Telangana,0.0,0.000000,0.17,-100.0
4,4,2009-01-01,2,Himachal Pradesh,0.0,0.008566,3.31,-100.0

In [12]:
rainfall.to_csv(
    "/content/rainfall_data.csv",
    index=False
)

print("Rainfall dataset saved!")

Rainfall dataset saved!

In [13]:
import os

print(os.path.getsize("/content/rainfall_data.csv") / (1024 * 1024), "MB")

10.47753620147705 MB